name: Build Tailscale Android (Universal)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-matrix:
    name: Build for ${{ matrix.goarch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goarch: arm64
            goarm: ''
            goos: linux 
            label: arm64-v8a

          - goarch: arm
            goarm: '7'
            goos: linux 
            label: armeabi-v7a

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: anasfanani/tailscale-android-cli
          #ref: v1.94.1  # Version
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Get Version
        id: get_ver
        run: |
          VERSION=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          
          echo "TS_VERSION=$VERSION" >> $GITHUB_ENV
          echo "âœ… Detected Version: $VERSION"

      - name: Build Binary (${{ matrix.label }})
        run: |
          export CGO_ENABLED=0
          export GOOS=${{ matrix.goos }}
          export GOARCH=${{ matrix.goarch }}
          export GOARM=${{ matrix.goarm }}
          
          echo "ðŸš€ Building $TS_VERSION for $GOOS/$GOARCH (Static)..."
  
          LDFLAGS="-s -w -X 'tailscale.com/version.longStamp=$TS_VERSION' -X 'tailscale.com/version.shortStamp=$TS_VERSION'"
          
          go build -trimpath -ldflags="$LDFLAGS" -o tailscaled ./cmd/tailscaled
          go build -trimpath -ldflags="$LDFLAGS" -o tailscale ./cmd/tailscale

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tailscale-${{ env.TS_VERSION }}-${{ matrix.goos }}-${{ matrix.label }}
          path: |
            tailscaled
            tailscale
